# TFM Extras Configuration File #

server:
  # The strength of the Jump Pads. Must be a positive whole number. Not recommended being greater than 10.
  jumppad_strength: 1
  # Admin Info Messages
  # These do not support legacy characters '&' and 'ยง', please refer to https://docs.adventure.kyori.net/minimessage/format.html
  admininfo:
    - "<red>I'm not inputting a preset admin info message."
  clear-on-join:
    - "Taahh"
  teleport-on-join:
    - "Taahh"
  allow-unsafe-enchantments: true
  clownfish:
    radius: 5
    strength: 2.5
    toggled_players:
      - "9285ace6-7393-45c5-9420-00fc66374ff4"
    restricted:
      - "9285ace6-7393-45c5-9420-00fc66374ff4"
player-worlds:
  size: 500